stages:
  - build
  - test
  - release
  - deploy

variables:
  API_TEST_IMAGE: registry.gitlab.com/mRokita/covidata-api:$CI_BUILD_REF_NAME
  API_RELEASE_IMAGE: registry.gitlab.com/mRokita/covidata-api:latest
  CRAWLER_TEST_IMAGE: registry.gitlab.com/mRokita/covidata-crawler:$CI_BUILD_REF_NAME
  CRAWLER_RELEASE_IMAGE: registry.gitlab.com/mRokita/covidata-crawler:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  tags:
    - private-shell
  script:
    - export IMAGE_TAG=$CI_BUILD_REF_NAME
    - docker-compose build
    - docker-compose push
test-api:
  stage: test
  tags:
    - private-shell
  script:
    - docker run $API_TEST_IMAGE "python -m pytest --cov=. /app/tests/ --cov-report term-missing"
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
release-api-image:
  stage: release
  tags:
    - private-shell
  script:
    - docker pull $API_TEST_IMAGE
    - docker tag $API_TEST_IMAGE $API_RELEASE_IMAGE
    - docker push $API_RELEASE_IMAGE
  only:
    - master
release-crawler-image:
  stage: release
  tags:
    - private-shell
  script:
    - docker pull $CRAWLER_TEST_IMAGE
    - docker tag $CRAWLER_TEST_IMAGE $CRAWLER_RELEASE_IMAGE
    - docker push $CRAWLER_RELEASE_IMAGE
  only:
    - master
deploy:
  stage: deploy
  when: manual
  only:
    - master
  tags:
    - private-shell
  script:
    - export IMAGE_TAG=latest
    - docker stack deploy --compose-file docker-compose.yml covidata