stages:
  - test
  - deploy
test:
  stage: test
  image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8
  script:
    - apk add --no-cache postgresql-libs postgresql-dev gcc python3-dev libffi-dev musl-dev
    - apk add --no-cache --virtual .build-deps make gcc musl-dev postgresql-dev
    - cd api
    - python -m pip install -r requirements.txt --no-cache-dir
    - cd app
    - python -m pytest --cov=. tests/ --cov-report term-missing
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

deploy:
  stage: deploy
  only:
    - master
  tags:
    - private-shell
  script:
    - docker-compose build
    - docker-compose push
    - docker stack deploy --compose-file docker-compose.yml covidata