stages:
  - test
  - deploy
test:
  stage: test
  image: alpine:3.11.5
  script:
    - apk add --no-cache postgresql-libs postgresql-dev gcc python3-dev musl-dev
    - apk add --no-cache --virtual .build-deps make gcc musl-dev postgresql-dev
    - cd api
    - pip install -r requirements.txt --no-cache-dir
    - cd app
    - python -m pytest

deploy:
  stage: deploy
  only:
    - master
  tags:
    - private-shell
  script:
    - docker-compose up -d --build