version: '3.5'
services:
  api:
    build:
      context: api/
    labels:
      - "traefik.enable=true"
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_USER: covidata
      POSTGRES_DB: covidata