"""add nullable false

Revision ID: 439c0e326cf9
Revises: 73bce5069427
Create Date: 2020-03-30 00:06:25.309259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439c0e326cf9'
down_revision = '73bce5069427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_recoveries', sa.Integer(), nullable=False))
        batch_op.alter_column('total_cases',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_deaths',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('is_poland',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_poland',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('day_reports', schema=None) as batch_op:
        batch_op.alter_column('total_deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_cases',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('total_recoveries')

    # ### end Alembic commands ###
