"""add downloaed global report

Revision ID: 534b0f2273db
Revises: 439c0e326cf9
Create Date: 2020-03-30 12:32:20.289925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534b0f2273db'
down_revision = '439c0e326cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloaded_global_reports',
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('downloaded_global_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloaded_global_reports_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloaded_global_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloaded_global_reports_date'))

    op.drop_table('downloaded_global_reports')
    # ### end Alembic commands ###
