"""empty message

Revision ID: 67a2029097d5
Revises: 91125fb986bd
Create Date: 2020-03-29 01:38:41.082356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2029097d5'
down_revision = '91125fb986bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('day_reports') as batch_op:
        batch_op.create_unique_constraint('unique_date_for_region',
                                          ['date', 'region_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('day_reports') as batch_op:
        batch_op.drop_constraint('unique_date_for_region', type_='unique')
    # ### end Alembic commands ###
