"""empty message

Revision ID: 73bce5069427
Revises: 67a2029097d5
Create Date: 2020-03-29 04:51:05.905592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from settings import DATABASE_URL

revision = '73bce5069427'
down_revision = '67a2029097d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('day_reports', schema=None) as batch_op:
        if not DATABASE_URL.startswith('sqlite'):
            batch_op.drop_constraint('day_reports_region_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('day_reports_region_id_fkey',
                                    'regions', ['region_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_reports', schema=None) as batch_op:
        batch_op.drop_constraint('day_reports_region_id_fkey', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
