"""empty message

Revision ID: 91125fb986bd
Revises: b557a5d2dc6d
Create Date: 2020-03-29 00:09:19.758760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91125fb986bd'
down_revision = 'b557a5d2dc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_day_reports_region_id'), 'day_reports', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_reports_region_id'), table_name='day_reports')
    # ### end Alembic commands ###
