"""add report_type to regions

Revision ID: a0eea3113cf2
Revises: e964f43a91b9
Create Date: 2020-04-04 01:58:45.929547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0eea3113cf2'
down_revision = 'e964f43a91b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloaded_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_downloaded_reports_date')
        batch_op.drop_index('ix_downloaded_reports_type')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.Enum('GLOBAL', 'LOCAL', name='reporttype'), nullable=False, server_default='GLOBAL'))
        batch_op.drop_column('is_poland')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_poland', sa.BOOLEAN(), autoincrement=False))
        batch_op.drop_column('report_type')

    with op.batch_alter_table('downloaded_reports', schema=None) as batch_op:
        batch_op.create_index('ix_downloaded_reports_type', ['type'], unique=False)
        batch_op.create_index('ix_downloaded_reports_date', ['date'], unique=False)

    # ### end Alembic commands ###
