"""empty message

Revision ID: b557a5d2dc6d
Revises: cb9d5edbe1f2
Create Date: 2020-03-28 22:40:11.513425

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b557a5d2dc6d'
down_revision = 'cb9d5edbe1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_day_reports_date'), 'day_reports', ['date'],
                    unique=False)
    op.drop_index('ix_day_reports_id', table_name='day_reports')
    with op.batch_alter_table('day_reports') as batch_op:
        batch_op.drop_column('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_reports_date'), table_name='day_reports')
    # ### end Alembic commands ###
