"""empty message

Revision ID: cb9d5edbe1f2
Revises: 35306ec594b0
Create Date: 2020-03-28 21:05:02.622909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9d5edbe1f2'
down_revision = '35306ec594b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
