"""remove pk on dreports

Revision ID: e964f43a91b9
Revises: d375d1626c20
Create Date: 2020-04-01 04:49:15.227424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from settings import DATABASE_URL

revision = 'e964f43a91b9'
down_revision = 'd375d1626c20'
branch_labels = None
depends_on = None


def upgrade():
    is_sqlite = DATABASE_URL.startswith('sqlite')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloaded_reports', schema=None) as batch_op:
        if not is_sqlite:
            batch_op.drop_constraint('downloaded_global_reports_pkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
